version: 2
jobs:
  build:
    docker:
      - image: nomaddo/cross-rpi
    steps:
      - checkout
      - run:
          name: get vc4c url
          command: curl "https://circleci.com/api/v1.1/project/github/doe300/VC4C/latest/artifacts?branch=master&filter=successful" --output /tmp/dump
      - run:
          name: get vc4cl-stdlib package
          command: wget -O /tmp/vc4cl-stdlib.deb $(python .circleci/get_url.py "vc4cl-stdlib-" "/tmp/dump")
      - run:
          name: get vc4c package
          command: wget -O /tmp/vc4c.deb $(python .circleci/get_url.py "vc4c-" "/tmp/dump")
      - run:
          name: unpack dependencies
          command: dpkg-deb -x /tmp/vc4cl-stdlib.deb /opt/raspberrypi/tools/arm-bcm2708/gcc-linaro-arm-linux-gnueabihf-raspbian-x64/arm-linux-gnueabihf/ && dpkg-deb -x /tmp/vc4c.deb /opt/raspberrypi/tools/arm-bcm2708/gcc-linaro-arm-linux-gnueabihf-raspbian-x64/arm-linux-gnueabihf/
      - run:
          name: configure
          command: cmake . -DCROSS_COMPILE=ON -DBUILD_TESTING=ON -DOpenCL_INCLUDE_DIR=/opt/rasberrypi/tools/arm-bcm2708/gcc-linaro-arm-linux-gnueabihf-raspbian-x64/arm-linux-gnueabihf/include -DOpenCL_LIBRARY=/opt/rasberrypi/tools/arm-bcm2708/gcc-linaro-arm-linux-gnueabihf-raspbian-x64/arm-linux-gnueabihf/include
      - run:
          name: build
          command: make -j2
      - run:
          name: deb-packing
          command: cpack -G DEB
      - store_artifacts:
          path: build/libVC4CL.so.0.4
          distination: libVC4CL.so.0.4
      - store_artifacts:
          path: build/test/TestVC4CL
          distination: TestVC4CL
      - store_artifacts:
          path: vc4cl-0.4-Linux.deb
          distination: vc4cl-0.4-Linux.deb
